language: node_js
node_js:
- node
install:
- npm install
script:
- npm run lint
- npm run test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: GW69oHDCh/WmmP+pEPD8G2WUrGNVDcLFReGqry5pTph2okXrY9RuYlQ0ptWkWCo+Dtu09XV0fIJMfIVi72FfiTk6q2kDQmIMY5zIzJzgpAP6bq0Fs2ScDucyZsTvvztYsXdb2Ik2xx77/Z0WCuxzfwgLyQ8vD4+E29r7Fe1pJlB/BdvE8hbQu5bhM3kV4hEJgP9q+dEjaN5K7+B63Bh/hRmnZNCaAXwqs/I4SZpJ7rf7GjjIgR+h1wmIEauY4W8FhPymj1pVjzH1+Sg+RZHkM8yByrNiiwDGia8qf/BdgZz6Vv5Lij8Te/RftLKtramq2BBdTUn7k93vIRTfh8tWVAwWtef5LCdrsZTefbAhLlcHjgGd3bismkz2PAxMRRZkT5vfIAhDpiZMk9Mmi7aLhnsBBdpp95fhu4qutJCnfTf5fTx3QRq7oWED7Ikvqe+HoZSmS+bZfW3aaFzuYEUJmsbo7Ksf7htVdex/Ga05mZufO4DmlrUsUDBYU8/WM2Uq4KaYgCoLUmMWBOkCXO76KWG84Bd8YRBKMVhF5e12iybz6BSIh9pobgrgefhh9mXtjWo9WCUFKJ8Us3fDiiolSHy1N/PZeaoFr+AdhCgFFGxXZBfW6y5p6xApmMc9sKeRYArrzyhg4P1WzUckuJjtw1ls8la8Ml/5qGYIl6UdU/E=
  app: react-webgl-starter