language: node_js
node_js:
- node
install:
- npm install
script:
- npm run lint
- npm run test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: jntZEA/MxxDd9uhsigpyui0FUGQoZ4kYz5s9nns1UCqcIZLkjvYSCNI6Ul+bY68fMWg6txKgwCE70oeZBKY0JCMWYYSPb/vqw9kx1Lfd/YdqwE/ydDZ+Bb1Q7W7Tk0gwBweRMwWr8CR3092JMuPvTbK6Xyv4ArwL9e7h2Tn8xF2mwDlQYXEPMbdM/mjRvwq9hodvvMENO6rzHBI2enhXNPYT4Lc9x8MZbGGT4Zj8Q8KxZe70I1+7q/JF9o3hnrR9JGw3ImoFAbuvup4hb/gfot8zqsfIPlekqoOO1fudr3z8AZYZOlIAuY6zkZwMoTkFQjsXbZSindvcNOnmlPtRCZSkc7FJpyAXP8iKIekoeh2+SK5A5S7Dsv9GArmY9lW9TD3H6v2L4lxX4Nugi20EZzdlNVCLOaC57cT9l7M5q/0e0xYszqknKWvN+rymUzKUAjn8j0LJ96w4jZgCDkUUcuCLV13AYMoNyK5lNehzUQ7ZDvk+/pK8nISfs1rqDxBx9yf9PBkyzbsWL38CEqSYEid1IFIo8C1bqHEgp6hjIJ4GzJEDorbZQoW77QWBxlw4dWN4Rwe6zUyg6ZRCMageV1g+9kRswIeMQGsI8FR+SmORE/FxWXzqoXl8Am99U/PmXktx6St/iKRi+d5urTHTHjrZFgynEFTbJzqw3+PRcoI=
  app: react-webgl-starter