language: node_js
node_js:
- node
install:
- npm install
script:
- npm run lint
- npm run test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: St5gc+actprYWxRVRgfUw1uzSq8n0dPbsIvJ43/g1lr3bR5wqB4vQplDiZ6GPdsq+FVh2TUl1cq0r0cZ4EjYjL538hWE2OuQJ+9nnznHf3wnNVOWxd3lrBTn7n40VNSjYa6EgSSHlZO/iQHLDGcUQxnZuAlb3Z2O08T4x0fnppijRLzye1SojP6/CuNqrCQuWhBoB+0+4dh05urcDdn96wK+GlcsiUCdKRHV8ipzOZMUL+Jl8JEw9sJDvig8Va/FmZTRNV3cCssqEDKmflGP5w/8b5QOutTrGTx6qiPsd9WoPEIRey71v+wmiqtZNJ+Cpjv0Riv1tqULLijzpP5Yfwv1/feneuX14fOtOzvrnvshvov8Z8L3bObh5xgwiEtf7esDPFogtgiLafWDm8DdyWUqpqsYgrX+aC2drVLEpeRz9CjcDo/k7jD5mpTvv2751gSGjwaDEmX7YhgOdIMNpzznvt/wdk1Iwf9rT0kuNl9DHMBYu/+0CJD0nrbNLEAxUWEy0L2ptb3ZlZQ9ks6TEGTquHDjdmfta8dN0QNWHRgIxBkqSEA0YyO+gleXfpaFKvIxuZnzxHJYZlrzJ/KeeDKhFP2lyzN6uA8xSv9OkWx5MrilIgxVybpca+VQ51mKO2B1JNm44nUmC1PC2zw/TYRGVgOAKsyX4dzq2v3U+eE=
  app: react-webgl-starter